#!/bin/bash
set -e

# Aggiorna database desktop
if command -v update-desktop-database &> /dev/null; then
    update-desktop-database
fi

# Aggiorna database icone
if command -v update-icon-caches &> /dev/null; then
    update-icon-caches /usr/share/icons/hicolor || true
fi

exit 0
